#%RAML 1.0 NamedExample
{
  "feedback" : {
    "productTitle": "SAMSUNG-A2-4GB-64GB",
		"Display":"Good",
		"Camera":"Good",
		"Performance":"Good",
		"Overall":"Good",
		"description":"Its good"
		},
	 "status": "Delivered"
}
